---
kind: pipeline
name: release
type: docker
trigger:
  branch:
    - master

steps:
  - name: release
    image: node:13
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - npm install
      - npx semantic-release
